Separate create and serve action

diff --git a/docker/root/usr/local/bin/serve b/docker/root/usr/local/bin/serve
--- a/docker/root/usr/local/bin/serve
+++ b/docker/root/usr/local/bin/serve
@@ -1,10 +1,82 @@
-#!/usr/bin/env sh
-set -e
+#!/usr/bin/env bash
 
-SPHINX_PATH=${SPHINX_PATH:-"$(pwd)/docs"}
+set -eo pipefail
 
-conffile="$(find "$SPHINX_PATH" -type f -name conf.py)"
-sourcedir="$(test -n "$conffile" && dirname "$conffile" || echo '.')"
+
+usage() {
+  cat 1>&2 <<-ENDOFUSAGE
+	Usage: $(basename "$0") --project-dir PATH [--extra DEP1 ... [--extra DEPN]] [--reinstall-deps]
+	
+	options:
+	  --project-dir PATH    path to the root directory with documentation
+	  --extra DEP           install additional dependency
+	  --reinstall-deps      reinstall all dependencies before starting the web server
+	
+	ENDOFUSAGE
+}
+
+
+projectDir=''
+extraDeps=()
+
+if pip freeze --user | grep -Fq "-e $(pwd)"; then
+  installDeps=false
+else
+  installDeps=true
+fi
+
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+      --extra)
+        extraDeps+=('-e' ".[$2]")
+        shift 2
+        ;;
+      -d|--project-dir)
+        projectDir="$2"
+        shift 2
+        ;;
+      --reinstall-deps)
+        installDeps=true
+        shift 1
+        ;;
+      -h|--help)
+        usage
+        exit 0
+        ;;
+      *)
+        echo >&2 "Error: Unknown option $1"
+        usage
+        exit 1
+        ;;
+    esac
+done
+
+if [[ -z "$projectDir" ]]; then
+  echo >&2 'Error: require option --project-dir'
+  usage
+  exit 1
+fi
+
+
+conffile="$(find "$projectDir" -type f -name conf.py 2>/dev/null || true)"
+
+if [ -z "$conffile" ]; then
+  echo >&2 "Sphinx configuration file (conf.py) not found in $projectDir"
+  exit 1
+fi
+
+
+if $installDeps; then
+  echo -e '\033[1mInstall project dependencies\033[0m'
+
+  if [[ -f requirements.txt ]]; then
+    pip install --user --no-warn-script-location -r requirements.txt
+  elif [[ -f pyproject.toml ]] || [[ -f setup.cfg ]] || [[ -f setup.py ]]; then
+    pip install --user --no-warn-script-location -e . "${extraDeps[@]}"
+  fi
+fi
+
+sourcedir="$(dirname "$conffile")"
 outdir='/tmp/build/html'
 
 sphinx-autobuild --host 0.0.0.0 "$sourcedir" "$outdir"
